'use client'

import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { toast } from 'sonner'

import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { ApiClientError, postJson } from '@/lib/client/api'

export function QrDialog({
  trigger,
  tableId,
  tableCode,
  svg,
  url,
  canRotate,
}: {
  trigger: React.ReactNode
  tableId: string
  tableCode: string
  /** Pre-rendered on the server so printing works with no client library. */
  svg: string
  url: string
  canRotate: boolean
}) {
  const router = useRouter()
  const [confirming, setConfirming] = useState(false)
  const [pending, setPending] = useState(false)

  async function rotate() {
    setPending(true)
    try {
      await postJson(`/api/tables/${tableId}/qr`, {})
      toast.success('New QR issued — reprint and replace the old sticker')
      setConfirming(false)
      router.refresh()
    } catch (cause) {
      toast.error(
        cause instanceof ApiClientError
          ? cause.message
          : 'Could not rotate the QR code.',
      )
    } finally {
      setPending(false)
    }
  }

  return (
    <Dialog>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>QR code for {tableCode}</DialogTitle>
          <DialogDescription>
            Print this and place it on the table. Diners scan it to open the
            menu and order.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Always on white regardless of theme — a dark-mode QR inverts the
              contrast scanners rely on and many will not read it. */}
          <div
            className="mx-auto w-48 rounded-lg bg-white p-3 [&>svg]:h-auto [&>svg]:w-full"
            // Generated by the `qrcode` library from our own token, on the
            // server. No user-supplied content reaches this markup.
            dangerouslySetInnerHTML={{ __html: svg }}
          />

          <p className="break-all text-center font-mono text-xs text-muted-foreground">
            {url}
          </p>

          {confirming && (
            <Alert variant="destructive">
              <AlertDescription>
                Issuing a new QR code invalidates the sticker currently on this
                table. Anyone scanning the old one will see nothing until you
                replace it.
              </AlertDescription>
            </Alert>
          )}
        </div>

        {canRotate && (
          <DialogFooter>
            {confirming ? (
              <>
                <Button
                  variant="outline"
                  onClick={() => setConfirming(false)}
                  disabled={pending}
                >
                  Cancel
                </Button>
                <Button
                  variant="destructive"
                  onClick={rotate}
                  disabled={pending}
                >
                  {pending ? 'Issuing…' : 'Yes, issue a new QR'}
                </Button>
              </>
            ) : (
              <Button variant="outline" onClick={() => setConfirming(true)}>
                Issue new QR code
              </Button>
            )}
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  )
}
