import { relations } from 'drizzle-orm'
import {
  index,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

import { restaurants } from './tenancy'
import { users } from './identity'
import { tenantPolicy, timestamps } from './_shared'

/**
 * Recommendations that have been answered.
 *
 * The advisor holds no state of its own: every recommendation is recomputed
 * from the data each time it is asked. Storing the findings would mean a
 * finding could outlive the fact behind it, and a stale recommendation is
 * worse than none — someone acts on it and discovers the situation resolved
 * itself a fortnight ago.
 *
 * What IS stored is the human answer to a recommendation. "We know, and here
 * is why we are not acting" is real information, and losing it means the same
 * argument is had every week until people stop reading the page.
 *
 * Rows are keyed on the insight's stable key rather than on its wording, so a
 * dismissal survives the numbers moving. A key that changed with the figures
 * would resurrect every dismissal the moment anything did.
 */
export const insightDismissals = pgTable(
  'insight_dismissals',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    restaurantId: uuid('restaurant_id')
      .notNull()
      .references(() => restaurants.id, { onDelete: 'cascade' }),

    /** e.g. `menu:dog:<uuid>`. Generated by the engine, stable across runs. */
    insightKey: text('insight_key').notNull(),

    /**
     * Required, and deliberately so.
     *
     * Dismissing is how an inconvenient finding is made to disappear. A reason
     * costs the person doing it ten seconds and gives everyone else the one
     * thing they need to judge whether it should have gone.
     */
    reason: text('reason').notNull(),

    /**
     * Null means dismissed for good; a date means snoozed until then.
     *
     * Both are needed. "We are already reordering that" wants a week's quiet;
     * "that dish is on the menu for the owner's mother" wants permanent quiet.
     * Offering only the second turns every temporary annoyance into a
     * permanent blind spot.
     */
    snoozedUntil: timestamp('snoozed_until', { withTimezone: true }),

    dismissedByUserId: uuid('dismissed_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),

    ...timestamps,
  },
  (t) => [
    /**
     * One answer per recommendation. Re-dismissing updates the reason rather
     * than stacking rows, so the current answer is always the only answer and
     * "why is this hidden?" has exactly one response.
     */
    uniqueIndex('insight_dismissals_key').on(t.restaurantId, t.insightKey),
    index('insight_dismissals_snoozed_idx').on(t.snoozedUntil),

    tenantPolicy('insight_dismissals_tenant_isolation', t.restaurantId),
  ],
)

export const insightDismissalsRelations = relations(
  insightDismissals,
  ({ one }) => ({
    dismissedBy: one(users, {
      fields: [insightDismissals.dismissedByUserId],
      references: [users.id],
    }),
  }),
)
