import { z } from 'zod'

/**
 * The insight key is generated by the engine, not typed by a user — but it
 * arrives over HTTP, so it is validated like anything else. Bounded to the
 * shapes the engine actually emits (`domain:kind` or `domain:kind:uuid`)
 * rather than accepting arbitrary text into a uniquely-indexed column.
 */
export const dismissInsightSchema = z.object({
  insightKey: z
    .string()
    .trim()
    .min(1)
    .max(120)
    .regex(
      /^[a-z]+:[a-z-]+(:[A-Za-z0-9-]+)?$/,
      'That is not a recognised recommendation.',
    ),
  /**
   * Required, and deliberately so — see the schema comment on the table. Ten
   * seconds from the person hiding a finding buys everyone else the one thing
   * they need to judge whether it should have gone.
   */
  reason: z
    .string()
    .trim()
    .min(1, 'Say why you are dismissing this')
    .max(500),
  /**
   * Absent means dismissed for good. Capped at a year: a snooze longer than
   * that is a permanent dismissal wearing a disguise, and should be recorded
   * as one so nobody is surprised when it never comes back.
   */
  snoozeDays: z.number().int().min(1).max(365).nullish(),
})

export type DismissInsightInput = z.infer<typeof dismissInsightSchema>
